import type { VtmDiscipline } from './vampiro'

// ────────────────────────────────────────────────────────
// Poderes das disciplinas (V5): nível, custo, teste, resistência, duração,
// amálgama (outra disciplina exigida), poder exigido e o livro de onde vem.
// O nome em português é tradução nossa; o original em inglês vai junto pra
// quem joga com o livro em inglês. Os resumos são nossos, curtos, só pra
// lembrar o que o poder faz; a regra completa está no livro. Resumo vazio =
// poder de suplemento que a gente ainda não descreveu.
// ────────────────────────────────────────────────────────

export type VtmBook =
  | 'core' | 'pg' | 'comp' | 'cbg' | 'cbn' | 'sab' | 'anarch' | 'cam' | 'tf' | 'gw' | 'fol' | 'wt'
  | 'cod' | 'bsl' | 'lsc' | 'fr' | 'bs' | 'ltsr' | 'im' | 'si' | 'bna' | 'cf' | 'cob' | 'tab'

export const VTM_BOOKS: Record<VtmBook, string> = {
  core:   'Livro Básico',
  pg:     'Players Guide',
  comp:   'Companion',
  cbg:    'Cults of the Blood Gods',
  cbn:    'Chicago by Night',
  sab:    'Sabbat: The Black Hand',
  anarch: 'Anarch',
  cam:    'Camarilla',
  tf:     'Tattered Façade',
  gw:     'Gehenna War',
  fol:    'Fall of London',
  wt:     "Winter's Teeth",
  cod:    'Courts of the Damned',
  bsl:    'Blood-Stained Love',
  lsc:    'Live from the Succubus Club',
  fr:     'Forbidden Religions',
  bs:     'Blood Sigils',
  ltsr:   'Let the Streets Run Red',
  im:     'In Memoriam',
  si:     'Second Inquisition',
  bna:    'Book of Nod Apocrypha',
  cf:     'Chicago Folios',
  cob:    'Children of Blood',
  tab:    'Trails of Ash and Bone',
}

/** Livros "principais": aparecem primeiro e sem o aviso de suplemento. */
export const VTM_MAIN_BOOKS = new Set<VtmBook>(['core', 'pg', 'comp', 'cbg', 'cbn'])

export interface VtmPower {
  /** "disciplina.chave" — o que vai pra ficha. */
  id:       string
  disc:     VtmDiscipline
  level:    number
  name:     string
  en:       string
  cost:     string
  pool:     string
  vs:       string
  duration: string
  /** Amálgama: precisa de N pontos nesta outra disciplina. */
  amalgam?: [VtmDiscipline, number]
  /** Poder(es) exigido(s) — basta ter um deles. */
  requires?: string[]
  books:    VtmBook[]
  summary:  string
}

const G = 'Grátis'
const R1 = '1 Despertar'
const R2 = '2 Despertares'
const NA = '—'
const PASS = 'Passivo'
const CENA = 'Uma cena'

type Row = [level: number, key: string, name: string, en: string, cost: string, pool: string, vs: string,
  duration: string, books: VtmBook[], summary: string, extra?: { amalgam?: [VtmDiscipline, number]; requires?: string[] }]

function build(disc: VtmDiscipline, rows: Row[]): VtmPower[] {
  return rows.map(([level, key, name, en, cost, pool, vs, duration, books, summary, extra]) => ({
    id: `${disc}.${key}`, disc, level, name, en, cost, pool, vs, duration, books, summary,
    amalgam: extra?.amalgam,
    requires: extra?.requires?.map((r) => (r.includes('.') ? r : `${disc}.${r}`)),
  }))
}

const ANIMALISMO = build('animalismo', [
  [1, 'vinculo_famulus', 'Vínculo Famulus', 'Bond Famulus', 'Alimentar o animal por 3 noites', 'Carisma + Empatia com Animais', NA, 'Permanente', ['core'],
    'Prende um animal a você pelo sangue: vira o seu famulus, leal e mais fácil de comandar.'],
  [1, 'sentir_a_besta', 'Sentir a Besta', 'Sense the Beast', G, 'Determinação + Animalismo', 'Autocontrole + Lábia', PASS, ['core'],
    'Percebe a Besta nos outros: quem é vampiro, quem está com fome ou perto do frenesi.'],
  [2, 'mensageiro_animal', 'Mensageiro Animal', 'Animal Messenger', R1, NA, NA, 'Uma ou mais noites', ['pg'],
    'Manda um animal levar uma mensagem ou um objeto pequeno a alguém.', { amalgam: ['auspicios', 1] }],
  [2, 'atavismo', 'Atavismo', 'Atavism', R1, 'Autocontrole + Animalismo', NA, 'Margem + 1 turnos', ['wt'],
    'Desperta a Besta de um animal: ele foge ou ataca.'],
  [2, 'sussurros_ferais', 'Sussurros Ferais', 'Feral Whispers', '1 Despertar (grátis com o famulus)', 'Manipulação ou Carisma + Animalismo', NA, CENA, ['core'],
    'Conversa com animais e chama ou dá ordens simples a eles.'],
  [2, 'coleira_na_besta', 'Coleira na Besta', 'Leash the Beast', '1 ou 2 Despertares', NA, NA, NA, ['lsc'],
    '', { amalgam: ['fortitude', 1] }],
  [2, 'rastro_do_sangue', 'Rastro do Sangue', 'Tracing the Blood', R1, 'Determinação + Animalismo', NA, CENA, ['cod'], ''],
  [3, 'comando_do_mensageiro', 'Comando do Mensageiro', "Messenger's Command", 'Como Dominação', 'Como Dominação', 'Como Dominação', 'Como Mensageiro Animal', ['pg'],
    'O mensageiro animal entrega também uma ordem de Compelir ou Hipnotizar.', { amalgam: ['dominacao', 1], requires: ['mensageiro_animal'] }],
  [3, 'suculencia_animal', 'Suculência Animal', 'Animal Succulence', G, NA, NA, PASS, ['core'],
    'Sangue animal mata mais Fome do que mataria.'],
  [3, 'praga_de_bestas', 'Praga de Bestas', 'Plague of Beasts', R1, 'Manipulação + Animalismo', 'Autocontrole + Empatia com Animais', 'Uma noite', ['pg'],
    'Marca uma pessoa: os animais da cidade passam a persegui-la e atrapalhar.'],
  [3, 'apaziguar_a_besta', 'Apaziguar a Besta', 'Quell the Beast', R1, 'Carisma + Animalismo', 'Vigor + Determinação', CENA, ['core'],
    'Acalma a Besta de alguém: mortais ficam apáticos, vampiros perdem o ímpeto (e podem sair do frenesi).'],
  [3, 'faro_de_presa', 'Faro de Presa', 'Scent of Prey', R1, 'Determinação + Animalismo', NA, CENA, ['sab'],
    'Rastreia pelo cheiro um mortal que viu uma quebra da Máscara.'],
  [3, 'colmeia_morta_viva', 'Colmeia Morta-Viva', 'Unliving Hive', G, NA, NA, PASS, ['core'],
    'Seu Animalismo vale para enxames de insetos, que podem morar no seu corpo.', { amalgam: ['ofuscacao', 2] }],
  [3, 'augurio', 'Augúrio', 'Augury', R1, 'Manipulação + Animalismo', NA, 'Alguns minutos', ['tf'],
    '', { amalgam: ['auspicios', 1], requires: ['colmeia_morta_viva'] }],
  [3, 'despertar_o_parasita', 'Despertar o Parasita', 'Awaken the Parasite', R1, 'Determinação + Animalismo', 'Autocontrole + Determinação', CENA, ['tf'],
    '', { requires: ['colmeia_morta_viva'] }],
  [4, 'subsumir_o_espirito', 'Subsumir o Espírito', 'Subsume the Spirit', '1 Despertar (grátis com o famulus)', 'Manipulação + Animalismo', NA, 'Uma cena ou mais', ['core'],
    'Possui o corpo de um animal; o seu fica parado como morto.'],
  [4, 'conduzir_o_rebanho', 'Conduzir o Rebanho', 'Sway the Flock', '1 ou mais Despertares', 'Autocontrole + Animalismo', NA, 'Uma noite', ['pg'],
    'Muda o humor de todos os animais de uma área: calmos ou agressivos.'],
  [5, 'dominio_animal', 'Domínio Animal', 'Animal Dominion', R2, 'Carisma + Animalismo', NA, 'Uma cena ou até cumprir a ordem', ['core'],
    'Comanda bandos e enxames inteiros de uma vez.'],
  [5, 'instigar_o_temperamento', 'Instigar o Temperamento Bestial', 'Coax the Bestial Temper', R1, 'Manipulação + Animalismo', NA, 'Enquanto cantarola', ['pg'],
    'Deixa as Bestas ao redor mais calmas ou mais irritadas (muda a dificuldade do frenesi).'],
  [5, 'arrancar_a_besta', 'Arrancar a Besta', 'Drawing Out the Beast', R1, 'Raciocínio + Animalismo', 'Autocontrole + Determinação', 'O frenesi', ['core'],
    'Joga o seu frenesi em outra pessoa, que surta no seu lugar.'],
  [5, 'caminhada_espiritual', 'Caminhada Espiritual', 'Spirit Walk', NA, NA, NA, 'Indefinida', ['gw'],
    '', { requires: ['subsumir_o_espirito'] }],
])

const AUSPICIOS = build('auspicios', [
  [1, 'sentidos_agucados', 'Sentidos Aguçados', 'Heightened Senses', G, 'Raciocínio + Auspícios', 'Determinação', 'Até desligar', ['core'],
    'Sentidos muito mais finos: soma Auspícios aos testes de percepção.'],
  [1, 'sentir_o_invisivel', 'Sentir o Invisível', 'Sense the Unseen', G, 'Raciocínio ou Determinação + Auspícios', NA, PASS, ['core'],
    'Percebe o sobrenatural: quem está oculto por Ofuscação, espíritos, magia.'],
  [2, 'panaceia', 'Panaceia', 'Panacea', R1, 'Autocontrole + Auspícios', NA, NA, ['comp', 'pg'],
    'Pelo toque, acalma a mente e recupera Força de Vontade de alguém.', { amalgam: ['fortitude', 1] }],
  [2, 'premonicao', 'Premonição', 'Premonition', 'Grátis ou 1 Despertar', 'Determinação + Auspícios', NA, 'Passivo ou ativo', ['core'],
    'Pressentimentos e visões; ativando, faz uma pergunta e recebe uma resposta em imagens.'],
  [2, 'revelar_temperamento', 'Revelar Temperamento', 'Reveal Temperament', R1, 'Inteligência + Auspícios', 'Autocontrole + Lábia', CENA, ['pg'],
    'Descobre a ressonância do sangue de um mortal (ou o clã de um vampiro) só observando.'],
  [2, 'perseguicao_implacavel', 'Perseguição Implacável', 'Unerring Pursuit', R1, 'Determinação + Auspícios', NA, 'Uma noite (+ uma por sucesso)', ['sab'],
    'Marca alguém e passa a saber por onde ele anda.', { amalgam: ['dominacao', 1] }],
  [3, 'visao_dos_vermes', 'Visão dos Vermes', 'Vermin Vision', R1, 'Determinação + Animalismo', NA, CENA, ['fol'],
    'Vê pelos olhos de ratos e outras pragas.', { amalgam: ['animalismo', 2] }],
  [3, 'falha_fatal', 'Falha Fatal', 'Fatal Flaw', R1, 'Inteligência + Auspícios', 'Autocontrole ou Vigor + Lábia', CENA, ['pg'],
    'Acha o ponto fraco do alvo: os ataques contra ele ficam mais perigosos.', { amalgam: ['oblivio', 1] }],
  [3, 'perscrutar_a_alma', 'Perscrutar a Alma', 'Scry the Soul', R1, 'Inteligência + Auspícios', 'Autocontrole + Lábia', 'Um turno', ['core'],
    'Lê a aura: humor, se é vampiro, se tem diablerie nas costas.'],
  [3, 'compartilhar_os_sentidos', 'Compartilhar os Sentidos', 'Share the Senses', R1, 'Determinação + Auspícios', NA, CENA, ['core'],
    'Vê e ouve pelos sentidos de alguém que já bebeu do seu sangue.'],
  [3, 'aruspice', 'Arúspice', 'Haruspex', R1, 'Determinação + Auspícios', NA, 'Uma noite', ['tf'],
    '', { amalgam: ['oblivio', 1] }],
  [3, 'ler_o_ambiente', 'Ler o Ambiente', 'Read the Room', R1, 'Inteligência + Auspícios', NA, 'Instantâneo', ['cod'], ''],
  [3, 'revelar_a_coleira', 'Revelar a Coleira Invisível', 'Reveal the Invisible Leash', R1, 'Inteligência + Auspícios', 'Autocontrole + Determinação', 'Enquanto toca', ['cod'], ''],
  [4, 'toque_do_espirito', 'Toque do Espírito', "Spirit's Touch", R1, 'Inteligência + Auspícios', NA, 'Um turno', ['core'],
    'Lê as emoções e lembranças que ficaram num objeto ou lugar.'],
  [4, 'coracao_exposto', 'Coração Exposto', 'Heart Laid Bare', R1, 'Inteligência + Auspícios', 'Autocontrole + Lábia', NA, ['tf'], ''],
  [5, 'clarividencia', 'Clarividência', 'Clairvoyance', R1, 'Inteligência + Auspícios', NA, 'De minutos a uma noite', ['core'],
    'Observa à distância um lugar que você conhece.'],
  [5, 'possessao', 'Possessão', 'Possession', R2, 'Determinação + Auspícios', 'Determinação + Inteligência', 'Até encerrar', ['core'],
    'Toma o corpo de um mortal.', { amalgam: ['dominacao', 3] }],
  [5, 'telepatia', 'Telepatia', 'Telepathy', '1 Despertar (+1 FV contra vampiro que não quer)', 'Determinação + Auspícios', 'Raciocínio + Lábia', 'Um minuto por Despertar', ['core'],
    'Lê pensamentos e conversa mente a mente.'],
  [5, 'aliviar_a_alma_bestial', 'Aliviar a Alma Bestial', 'Unburdening the Bestial Soul', '2 Despertares + 1 mancha', 'Autocontrole + Auspícios', NA, 'Uma sessão', ['comp', 'pg'],
    'Protege a Humanidade de outra pessoa, tirando manchas dela.', { amalgam: ['dominacao', 3], requires: ['panaceia'] }],
])

const CELERIDADE = build('celeridade', [
  [1, 'graca_felina', 'Graça Felina', "Cat's Grace", G, NA, NA, PASS, ['core'],
    'Equilíbrio perfeito: anda em beirais e cordas sem teste.'],
  [1, 'rapidez_fluente', 'Rapidez Fluente', 'Fluent Swiftness', G, NA, NA, 'Uma vez por teste', ['gw'], ''],
  [1, 'reflexos_rapidos', 'Reflexos Rápidos', 'Rapid Reflexes', G, NA, NA, PASS, ['core'],
    'Ações menores sem penalidade e defesa contra tiros mesmo sem cobertura.'],
  [2, 'ligeireza', 'Ligeireza', 'Fleetness', R1, 'Destreza + Celeridade', NA, CENA, ['core'],
    'Soma Celeridade aos testes de Destreza fora de combate e à defesa.'],
  [2, 'trabalho_as_pressas', 'Trabalho às Pressas', 'Rush Job', R1, NA, NA, CENA, ['pg'],
    'Faz uma tarefa demorada num instante.'],
  [3, 'piscar', 'Piscar', 'Blink', R1, 'Destreza + Atletismo', NA, 'Um turno', ['core'],
    'Cruza uma distância curta num piscar e já age do outro lado.'],
  [3, 'travessia', 'Travessia', 'Traversal', R1, 'Destreza + Atletismo', NA, 'Um turno', ['core'],
    'Corre por paredes e sobre a água.'],
  [3, 'tecer', 'Tecer', 'Weaving', R1, 'Celeridade (contra tiros)', NA, CENA, ['pg'],
    'Soma Celeridade à defesa contra armas de fogo.', { requires: ['reflexos_rapidos'] }],
  [3, 'mil_cortes', 'Mil Cortes', 'A Thousand Cuts', R1, 'Celeridade + Briga ou Armas Brancas', NA, 'Uma ação', ['tf'], ''],
  [4, 'impulso_borrado', 'Impulso Borrado', 'Blurred Momentum', '1 Despertar por turno', NA, NA, 'Até cessar', ['pg'],
    'Ataques com poucos sucessos simplesmente não te acertam.'],
  [4, 'gole_de_elegancia', 'Gole de Elegância', 'Draught of Elegance', R1, NA, NA, 'Uma noite', ['core'],
    'Quem bebe do seu sangue ganha a sua Celeridade por uma noite.'],
  [4, 'mira_infalivel', 'Mira Infalível', 'Unerring Aim', R1, NA, NA, 'Um ataque', ['core'],
    'Um tiro em que o mundo parece parado: o alvo não se defende.', { amalgam: ['auspicios', 2] }],
  [4, 'golpe_invisivel', 'Golpe Invisível', 'Unseen Strike', R2, 'Destreza + Celeridade', 'Raciocínio + Percepção', 'Um turno', ['pg'],
    'Some, ataca e some de novo.', { amalgam: ['ofuscacao', 4], requires: ['piscar'] }],
  [4, 'mais_rapido_que_a_luz', 'Mais Rápido que a Luz', 'Faster than Light', R1, NA, NA, 'Uma ação', ['lsc'],
    '', { requires: ['piscar'] }],
  [5, 'golpe_relampago', 'Golpe Relâmpago', 'Lightning Strike', R1, NA, NA, 'Um ataque', ['core'],
    'Um ataque tão rápido que só quem também tem Celeridade se defende.'],
  [5, 'fracao_de_segundo', 'Fração de Segundo', 'Split Second', R1, NA, NA, 'Uma ação', ['core'],
    'Age antes que algo aconteça, mudando o que o Narrador acabou de descrever.'],
])

const DOMINACAO = build('dominacao', [
  [1, 'nublar_a_memoria', 'Nublar a Memória', 'Cloud Memory', G, 'Carisma + Dominação', 'Raciocínio + Determinação', 'Indefinida', ['core'],
    'Faz o alvo esquecer os últimos minutos.'],
  [1, 'compelir', 'Compelir', 'Compel', G, 'Carisma + Dominação', 'Inteligência + Determinação', CENA, ['core'],
    'Uma ordem curta que o alvo cumpre na hora.'],
  [1, 'devocao_servil', 'Devoção Servil', 'Slavish Devotion', G, NA, NA, PASS, ['cbg', 'pg'],
    'Quem está preso a você resiste a ser dominado por outros.', { amalgam: ['fortitude', 1] }],
  [2, 'hipnotizar', 'Hipnotizar', 'Mesmerize', R1, 'Manipulação + Dominação', 'Inteligência + Determinação', 'Até cumprir ou a cena acabar', ['core'],
    'Ordens longas e detalhadas que o alvo cumpre.'],
  [2, 'demencia', 'Demência', 'Dementation', '1 Despertar por alvo por cena', 'Manipulação + Dominação', 'Autocontrole + Inteligência', CENA, ['core'],
    'Empurra a mente do alvo pra loucura: pânico, delírio, paranoia.', { amalgam: ['ofuscacao', 2] }],
  [2, 'favor_do_domitor', 'Favor do Domitor', "Domitor's Favor", R1, NA, NA, 'Um mês', ['comp', 'pg'],
    'Seus carniçais têm muito mais dificuldade de te desobedecer.'],
  [2, 'a_voz_roubada', 'A Voz Roubada', 'The Stolen Voice', R1, 'Autocontrole + Dominação', 'Determinação + Performance', CENA, ['tf'], ''],
  [3, 'mente_esquecida', 'Mente Esquecida', 'Forgetful Mind', R1, 'Manipulação + Dominação', 'Inteligência + Determinação', 'Indefinida', ['core'],
    'Reescreve lembranças inteiras do alvo.'],
  [3, 'diretiva_submersa', 'Diretiva Submersa', 'Submerged Directive', G, NA, NA, 'Até cumprir', ['core'],
    'Uma ordem guardada que o alvo cumpre depois, sem saber de onde veio.', { requires: ['hipnotizar'] }],
  [3, 'cadeia_de_comando', 'Cadeia de Comando', 'Chain of Command', R1, NA, NA, 'Até cumprir ou a cena acabar', ['cod'],
    '', { requires: ['hipnotizar'] }],
  [4, 'dominio_ancestral', 'Domínio Ancestral', 'Ancestral Dominion', R1, 'Manipulação + Dominação', 'Determinação + Ocultismo', 'Até cumprir ou a cena acabar', ['cbg', 'pg'],
    'Domina vampiros que descendem da sua linhagem.', { amalgam: ['feiticaria', 2], requires: ['hipnotizar'] }],
  [4, 'implantar_sugestao', 'Implantar Sugestão', 'Implant Suggestion', R1, 'Manipulação + Dominação', 'Autocontrole + Determinação', CENA, ['pg'],
    'Muda de leve a personalidade ou a opinião do alvo.', { amalgam: ['presenca', 1] }],
  [4, 'racionalizar', 'Racionalizar', 'Rationalize', G, NA, NA, 'Indefinida', ['core'],
    'Quem você domina acredita que agiu por vontade própria.'],
  [4, 'tabula_rasa', 'Tábula Rasa', 'Tabula Rasa', R2, 'Determinação + Dominação', 'Autocontrole + Determinação', 'Permanente', ['sab'],
    'Apaga a identidade inteira do alvo.'],
  [5, 'chamado_de_lete', 'Chamado de Lete', "Lethe's Call", R1, 'Manipulação + Dominação', 'Inteligência + Determinação', 'Indefinida', ['gw'],
    '', { requires: ['nublar_a_memoria', 'mente_esquecida'] }],
  [5, 'manipulacao_em_massa', 'Manipulação em Massa', 'Mass Manipulation', '+1 Despertar', 'Como o poder', 'Como o poder', 'Como o poder', ['core'],
    'Usa um poder de Dominação num grupo inteiro de uma vez.'],
  [5, 'decreto_terminal', 'Decreto Terminal', 'Terminal Decree', 'Grátis (gera manchas)', NA, NA, PASS, ['core'],
    'Suas ordens podem levar o alvo a ferir a si mesmo ou morrer.'],
])

const FORTITUDE = build('fortitude', [
  [1, 'resistencia_fluente', 'Resistência Fluente', 'Fluent Endurance', G, NA, NA, 'Uma vez', ['gw'], ''],
  [1, 'resiliencia', 'Resiliência', 'Resilience', G, NA, NA, PASS, ['core'],
    'Soma os pontos de Fortitude à Vitalidade (a ficha já conta sozinha).'],
  [1, 'mente_inabalavel', 'Mente Inabalável', 'Unswayable Mind', G, NA, NA, PASS, ['core'],
    'Soma Fortitude pra resistir a coerção e controle da mente.'],
  [2, 'perseveranca_da_terra', 'Perseverança da Terra', "Earth's Perseverance", R1, NA, NA, 'Uma cena ou até soltar', ['pg'],
    'Fica plantado como pedra: ninguém te derruba nem te move.'],
  [2, 'bestas_resistentes', 'Bestas Resistentes', 'Enduring Beasts', R1, 'Vigor + Animalismo', NA, CENA, ['core'],
    'Dá resistência sobrenatural aos seus animais.', { amalgam: ['animalismo', 1] }],
  [2, 'vitae_revigorante', 'Vitae Revigorante', 'Invigorating Vitae', 'Só o Despertar', NA, NA, PASS, ['pg'],
    'Seu sangue cura mortais que o bebem.', { amalgam: ['auspicios', 1] }],
  [2, 'obstinado', 'Obstinado', 'Obdurate', R1, 'Raciocínio + Sobrevivência', NA, CENA, ['wt'], '', { amalgam: ['potencia', 2] }],
  [2, 'robustez', 'Robustez', 'Toughness', R1, NA, NA, CENA, ['core'],
    'Diminui o dano superficial que você recebe.'],
  [2, 'autoconfianca', 'Autoconfiança', 'Self-Assurance', R1, NA, NA, CENA, ['lsc'], '', { requires: ['mente_inabalavel'] }],
  [3, 'desafiar_a_perdicao', 'Desafiar a Perdição', 'Defy Bane', R1, 'Raciocínio + Sobrevivência', NA, 'Uma cena ou até gastar', ['core'],
    'Transforma dano agravado (fogo, sol) em superficial.'],
  [3, 'fortificar_a_fachada', 'Fortificar a Fachada Interior', 'Fortify the Inner Façade', G, NA, NA, CENA, ['core'],
    'Protege a mente contra quem tenta ler você.'],
  [3, 'selar_a_boca_da_besta', 'Selar a Boca da Besta', "Seal Beast's Maw", R2, NA, NA, CENA, ['fr'], ''],
  [3, 'valeren', 'Valeren', 'Valeren', R1, 'Inteligência + Fortitude', NA, NA, ['comp', 'pg'],
    'Cura pelo toque o dano de outro vampiro.', { amalgam: ['auspicios', 1] }],
  [3, 'alma_calejada', 'Alma Calejada', 'Calloused Soul', '2 manchas', NA, NA, 'Uma noite', ['tf'], ''],
  [4, 'gole_de_resistencia', 'Gole de Resistência', 'Draught of Endurance', '1 Despertar por quem bebe', NA, NA, 'Uma noite', ['core'],
    'Quem bebe do seu sangue ganha a sua Fortitude por uma noite.'],
  [4, 'escamas_da_gorgona', 'Escamas da Górgona', "Gorgon's Scales", R1, NA, NA, 'Uma cena', ['pg'],
    'A pele endurece contra um tipo de ameaça, conforme o sangue que bebeu.'],
  [4, 'estilhacar', 'Estilhaçar', 'Shatter', R1, NA, NA, 'Uma cena ou até ser atingido', ['cbg'],
    'O dano que você segurou volta pra quem te bateu.', { requires: ['robustez'] }],
  [5, 'carne_de_marmore', 'Carne de Mármore', 'Flesh of Marble', R2, NA, NA, CENA, ['core'],
    'Ignora o primeiro golpe de cada turno (o sol ainda queima).'],
  [5, 'forca_pela_dor', 'Força pela Dor', 'Prowess from Pain', R1, NA, NA, CENA, ['core'],
    'Quanto mais ferido, mais fortes ficam os seus atributos.'],
  [5, 'escudos_de_carne', 'Escudos de Carne', 'Meat Shields', R1, NA, NA, CENA, ['tf'], ''],
])

const OFUSCACAO = build('ofuscacao', [
  [1, 'manto_de_sombras', 'Manto de Sombras', 'Cloak of Shadows', G, NA, NA, CENA, ['core'],
    'Fica invisível enquanto parado num lugar com alguma cobertura.'],
  [1, 'esconder_objeto', 'Esconder Objeto', 'Ensconce', G, NA, NA, CENA, ['gw'], ''],
  [1, 'silencio_da_morte', 'Silêncio da Morte', 'Silence of Death', G, NA, NA, CENA, ['core'],
    'Você não faz barulho nenhum.'],
  [1, 'mascara_das_eras', 'Máscara das Eras', 'Mask of Ages', R1, NA, NA, 'Até o amanhecer', ['lsc'], ''],
  [2, 'esconderijo', 'Esconderijo', 'Cache', R1, NA, NA, 'Uma cena ou até o amanhecer', ['gw'], '', { requires: ['esconder_objeto'] }],
  [2, 'quimerismo', 'Quimerismo', 'Chimerstry', R1, 'Manipulação + Ofuscação', 'Autocontrole + Raciocínio', 'Um turno', ['comp', 'pg'],
    'Uma ilusão rápida, para um só sentido.', { amalgam: ['presenca', 1] }],
  [2, 'passagem_do_fantasma', 'Passagem do Fantasma', "Ghost's Passing", R1, NA, NA, 'Uma sessão', ['fr'], '', { amalgam: ['animalismo', 1] }],
  [2, 'passagem_invisivel', 'Passagem Invisível', 'Unseen Passage', R1, NA, NA, 'Uma cena ou até ser notado', ['core'],
    'Continua invisível mesmo se movendo.'],
  [2, 'ventriloquismo', 'Ventriloquismo', 'Ventriloquism', R1, 'Raciocínio + Ofuscação', 'Determinação + Autocontrole', CENA, ['fol'],
    'Só quem você escolhe ouve a sua voz.', { amalgam: ['auspicios', 2] }],
  [2, 'duplo_sentido', 'Duplo Sentido', 'Doubletalk', R1, 'Autocontrole + Ofuscação', 'Raciocínio + Auspícios', 'Uma fala', ['bsl'],
    'Esconde uma mensagem numa frase que só o alvo entende.', { amalgam: ['auspicios', 1] }],
  [3, 'fata_morgana', 'Fata Morgana', 'Fata Morgana', R1, 'Manipulação + Ofuscação', NA, CENA, ['comp', 'pg'],
    'Ilusões grandes e duradouras.', { amalgam: ['presenca', 2] }],
  [3, 'fantasma_na_maquina', 'Fantasma na Máquina', 'Ghost in the Machine', G, NA, NA, 'Como o poder', ['core'],
    'A Ofuscação engana também câmeras e gravações.'],
  [3, 'mascara_de_mil_faces', 'Máscara de Mil Faces', 'Mask of a Thousand Faces', R1, NA, NA, CENA, ['core'],
    'Quem olha vê outra pessoa, comum e esquecível.'],
  [3, 'mascara_do_isolamento', 'Máscara do Isolamento', 'Mask of Isolation', R1, 'Manipulação + Ofuscação', 'Carisma + Intuição', 'Uma ou mais noites', ['sab'],
    '', { amalgam: ['dominacao', 1], requires: ['mascara_de_mil_faces'] }],
  [3, 'labirinto_mental', 'Labirinto Mental', 'Mental Maze', '1 a 3 Despertares', 'Carisma + Ofuscação', 'Raciocínio + Determinação', 'Uma noite', ['cbg', 'pg'],
    'O alvo não consegue achar a saída de um lugar.', { amalgam: ['dominacao', 1] }],
  [3, 'mascara_mental', 'Máscara Mental', 'Mind Masque', R1, 'Inteligência + Ofuscação', NA, CENA, ['pg'],
    'Esconde seus pensamentos e emoções, ou mostra falsos.', { amalgam: ['dominacao', 2] }],
  [3, 'disfarce_do_falecido', 'Disfarce do Falecido', 'Guise of the Departed', R1, 'Raciocínio + Ofuscação', NA, 'Até o amanhecer', ['tf'],
    '', { amalgam: ['oblivio', 1] }],
  [4, 'ocultar', 'Ocultar', 'Conceal', R1, 'Inteligência + Ofuscação', NA, 'Uma ou mais noites', ['core'],
    'Esconde um objeto grande: um carro, uma porta, uma casa.', { amalgam: ['auspicios', 3] }],
  [4, 'desaparecer', 'Desaparecer', 'Vanish', 'Variável', 'Raciocínio + Ofuscação', 'Raciocínio + Percepção', 'Variável', ['core'],
    'Some mesmo com alguém olhando direto pra você.', { requires: ['manto_de_sombras'] }],
  [4, 'reclusao', 'Reclusão', 'Seclusion', R1, 'Manipulação + Ofuscação', 'Determinação + Percepção', 'Variável', ['tf'],
    '', { amalgam: ['dominacao', 1] }],
  [5, 'ocultar_a_reuniao', 'Ocultar a Reunião', 'Cloak the Gathering', '1 ou mais Despertares', NA, NA, 'Como o poder', ['core'],
    'Estende a sua Ofuscação a um grupo.'],
  [5, 'disfarce_do_impostor', 'Disfarce do Impostor', "Impostor's Guise", R1, 'Raciocínio + Ofuscação', 'Manipulação + Performance', CENA, ['core'],
    'Assume a aparência de uma pessoa específica.', { requires: ['mascara_de_mil_faces'] }],
])

const POTENCIA = build('potencia', [
  [1, 'forca_fluente', 'Força Fluente', 'Fluent Strength', G, NA, NA, 'Uma vez', ['gw'], ''],
  [1, 'corpo_letal', 'Corpo Letal', 'Lethal Body', G, NA, NA, PASS, ['core'],
    'Seus golpes desarmados fazem dano agravado em mortais e ignoram armadura.'],
  [1, 'salto_altissimo', 'Salto Altíssimo', 'Soaring Leap', G, NA, NA, PASS, ['core'],
    'Salta distâncias enormes.'],
  [2, 'proeza', 'Proeza', 'Prowess', R1, NA, NA, CENA, ['core'],
    'Soma Potência ao dano desarmado e de armas brancas, e aos testes de Força.'],
  [2, 'pegada_implacavel', 'Pegada Implacável', 'Relentless Grasp', R1, NA, NA, CENA, ['pg'],
    'Agarra com uma força impossível de soltar.'],
  [3, 'alimentacao_brutal', 'Alimentação Brutal', 'Brutal Feed', G, NA, NA, 'Uma alimentação', ['core'],
    'Bebe todo o sangue de alguém em segundos.'],
  [3, 'exuberancia', 'Exuberância', 'Exuberance', G, NA, NA, PASS, ['tf'], ''],
  [3, 'centelha_de_furia', 'Centelha de Fúria', 'Spark of Rage', R1, NA, NA, CENA, ['core'],
    'Acende a raiva e a violência num grupo.', { amalgam: ['presenca', 3] }],
  [3, 'aperto_sobrenatural', 'Aperto Sobrenatural', 'Uncanny Grip', R1, NA, NA, CENA, ['core'],
    'Escala qualquer superfície e se segura em qualquer coisa.'],
  [3, 'destruidor', 'Destruidor', 'Wrecker', G, NA, NA, 'Como a Proeza', ['pg'],
    'A Proeza vale em dobro pra quebrar objetos e estruturas.', { requires: ['proeza'] }],
  [4, 'gole_de_forca', 'Gole de Força', 'Draught of Might', R1, NA, NA, 'Uma noite', ['core'],
    'Quem bebe do seu sangue ganha a sua Potência por uma noite.'],
  [4, 'queda_esmagadora', 'Queda Esmagadora', 'Crash Down', R1, 'Força + Potência', 'Destreza + Atletismo', NA, ['pg'],
    'Cai de um salto atingindo tudo em volta.', { requires: ['salto_altissimo'] }],
  [5, 'choque_na_terra', 'Choque na Terra', 'Earth Shock', R2, NA, NA, 'Um uso por cena', ['core'],
    'Um golpe no chão derruba todos ao redor.'],
  [5, 'punho_de_caim', 'Punho de Caim', 'Fist of Caine', R1, NA, NA, CENA, ['core'],
    'Seus golpes desarmados fazem dano agravado até em vampiros.'],
  [5, 'martelo_sutil', 'Martelo Sutil', 'Subtle Hammer', G, NA, NA, PASS, ['pg'],
    'Usa toda a força sem quebrar o que não quer.'],
])

const PRESENCA = build('presenca', [
  [1, 'fascinio', 'Fascínio', 'Awe', G, NA, NA, CENA, ['core'],
    'As pessoas querem te agradar: soma Presença a testes de convencer e encantar.'],
  [1, 'intimidar', 'Intimidar', 'Daunt', G, NA, NA, CENA, ['core'],
    'Ninguém quer te enfrentar: soma Presença à intimidação.'],
  [1, 'olhos_da_serpente', 'Olhos da Serpente', 'Eyes of the Serpent', G, 'Carisma + Presença', 'Raciocínio + Autocontrole', 'Até desviar o olhar', ['anarch', 'pg'],
    'Paralisa quem cruza o seu olhar.', { amalgam: ['metamorfose', 1] }],
  [2, 'beijo_persistente', 'Beijo Persistente', 'Lingering Kiss', G, NA, NA, 'Várias noites', ['core', 'comp'],
    'Quem você morde fica viciado no seu beijo.'],
  [2, 'melpomene', 'Melpômene', 'Melpominee', G, 'Carisma + Presença', NA, NA, ['pg'],
    'Usa Presença pela voz, mesmo sem ser visto.'],
  [2, 'isca_do_predador', 'Isca do Predador', "Predator's Lure", R1, 'Carisma + Liderança', 'Autocontrole + Determinação', CENA, ['cod'], ''],
  [3, 'limpar_o_campo', 'Limpar o Campo', 'Clear the Field', R1, 'Autocontrole + Presença', 'Raciocínio + Autocontrole', NA, ['fol'],
    'Faz todo mundo sair de um lugar.', { amalgam: ['dominacao', 3] }],
  [3, 'olhar_aterrador', 'Olhar Aterrador', 'Dread Gaze', R1, 'Carisma + Presença', 'Autocontrole + Determinação', 'Um turno', ['core'],
    'Um olhar que paralisa de medo ou faz fugir.'],
  [3, 'encantamento', 'Encantamento', 'Entrancement', R1, 'Carisma + Presença', 'Autocontrole + Raciocínio', 'Uma hora + margem', ['core'],
    'O alvo fica encantado e quer te agradar a todo custo.'],
  [3, 'sanguessuga_de_paixao', 'Sanguessuga de Paixão', 'Passion Leech', R1, 'Autocontrole + Auspícios', NA, 'Até o pôr do sol', ['tf'],
    '', { amalgam: ['auspicios', 2] }],
  [3, 'voz_projetada', 'Voz Projetada', 'Thrown Voice', R1, NA, NA, CENA, ['pg'], '', { amalgam: ['auspicios', 1] }],
  [3, 'rosto_do_amor', 'Rosto do Amor Verdadeiro', "True Love's Face", R1, 'Manipulação + Presença', 'Autocontrole + Raciocínio', CENA, ['cbg'],
    'O alvo te vê como alguém que ele ama (ou teme).', { amalgam: ['ofuscacao', 3] }],
  [3, 'exibicao_revigorante', 'Exibição Revigorante', 'Invigorating Display', R1, 'Autocontrole + Presença', NA, CENA, ['lsc'], '', { requires: ['fascinio'] }],
  [4, 'inflamar_o_desejo', 'Inflamar o Desejo', 'Inflame Desire', R1, 'Manipulação + Presença', 'Autocontrole + Determinação', CENA, ['tf'],
    '', { amalgam: ['ofuscacao', 1] }],
  [4, 'voz_irresistivel', 'Voz Irresistível', 'Irresistible Voice', G, NA, NA, PASS, ['core'],
    'Sua Dominação funciona só pela voz, sem olhar nos olhos.', { amalgam: ['dominacao', 1] }],
  [4, 'magnum_opus', 'Magnum Opus', 'Magnum Opus', '1 ou mais Despertares', 'Carisma ou Manipulação + Ofícios', NA, NA, ['wt'],
    '', { amalgam: ['auspicios', 3] }],
  [4, 'impregnar_o_edificio', 'Impregnar o Edifício', 'Suffuse the Edifice', 'Variável', 'Como o poder', 'Como o poder', 'Como o poder', ['pg'],
    'Um poder de Presença atinge todos dentro de um prédio.'],
  [4, 'convocar', 'Convocar', 'Summon', R1, 'Manipulação + Presença', 'Autocontrole + Inteligência', 'Uma noite', ['core'],
    'Chama alguém que você já conheceu: ele vem até você.'],
  [4, 'parceiro', 'Parceiro', 'Wingman', '1 Despertar + o do poder', NA, NA, 'Como o poder', ['bsl'], ''],
  [5, 'majestade', 'Majestade', 'Majesty', R2, 'Carisma + Presença', 'Autocontrole + Determinação', CENA, ['core'],
    'Ninguém consegue agir contra você; todos ficam em reverência.'],
  [5, 'magnetismo_estelar', 'Magnetismo Estelar', 'Star Magnetism', '+1 Despertar', NA, NA, 'Como o poder', ['core'],
    'Sua Presença funciona por vídeo, transmissões e gravações.'],
])

const METAMORFOSE = build('metamorfose', [
  [1, 'olhos_da_besta', 'Olhos da Besta', 'Eyes of the Beast', G, NA, NA, 'Quanto quiser', ['core'],
    'Enxerga no escuro total (os olhos brilham).'],
  [1, 'contorcer', 'Contorcer', 'Squirm', 'Grátis ou 1 Despertar', NA, NA, 'Quanto quiser', ['tf'], ''],
  [1, 'peso_da_pena', 'Peso da Pena', 'Weight of the Feather', G, 'Raciocínio + Sobrevivência', NA, 'Quanto quiser', ['core'],
    'Fica levíssimo: não sofre dano de queda.'],
  [2, 'armas_ferais', 'Armas Ferais', 'Feral Weapons', R1, NA, NA, CENA, ['core'],
    'Garras e presas viram armas: mais dano, agravado contra mortais.'],
  [2, 'vicissitude', 'Vicissitude', 'Vicissitude', R1, 'Determinação + Metamorfose', NA, 'Permanente', ['pg'],
    'Molda a própria carne e os próprios ossos.', { amalgam: ['dominacao', 2] }],
  [2, 'beijo_da_serpente', 'Beijo da Serpente', "Serpent's Kiss", R1, NA, NA, CENA, ['bsl'], ''],
  [2, 'o_falso_gole', 'O Falso Gole', 'The False Sip', R1, NA, NA, 'Uma ou mais cenas', ['bsl'], '', { amalgam: ['fortitude', 1] }],
  [3, 'fusao_com_a_terra', 'Fusão com a Terra', 'Earth Meld', R1, NA, NA, 'Um dia ou mais', ['core'],
    'Afunda no chão e passa o dia lá dentro.'],
  [3, 'modelar_a_carne', 'Modelar a Carne', 'Fleshcrafting', R1, 'Determinação + Metamorfose', 'Vigor + Determinação', 'Permanente', ['pg'],
    'Molda a carne de outras pessoas.', { amalgam: ['dominacao', 2], requires: ['vicissitude'] }],
  [3, 'mudar_de_forma', 'Mudar de Forma', 'Shapechange', R1, NA, NA, CENA, ['core'],
    'Vira um animal de tamanho parecido com o seu (lobo, cão grande).'],
  [3, 'absorcao_visceral', 'Absorção Visceral', 'Visceral Absorption', R1, 'Força + Metamorfose', NA, 'Um turno por corpo', ['sab'],
    'Absorve corpos (e o sangue deles) pra dentro de você.', { amalgam: ['feiticaria', 2] }],
  [3, 'mascara_da_morte', 'Máscara da Morte', 'Masque of Death', R1, NA, NA, 'Até encerrar', ['lsc'],
    'Parece um cadáver.', { amalgam: ['oblivio', 2] }],
  [4, 'forma_horrenda', 'Forma Horrenda', 'Horrid Form', R1, NA, NA, CENA, ['pg'],
    'Vira uma criatura monstruosa de combate.', { amalgam: ['dominacao', 2], requires: ['vicissitude'] }],
  [4, 'metamorfose', 'Metamorfose', 'Metamorphosis', R1, NA, NA, CENA, ['core'],
    'Vira animais de qualquer tamanho: um pássaro, um rato, um urso.', { requires: ['mudar_de_forma'] }],
  [5, 'forma_de_sangue', 'Forma de Sangue', 'Blood Form', R1, NA, NA, CENA, ['gw'], '', { amalgam: ['feiticaria', 2] }],
  [5, 'coracao_das_trevas', 'O Coração das Trevas', 'The Heart of Darkness', G, NA, NA, 'Permanente', ['cbg'],
    'Arranca o próprio coração e o esconde: estaca no peito não te para.', { amalgam: ['fortitude', 2] }],
  [5, 'mestre_das_formas', 'Mestre das Formas', 'Master of Forms', 'Como Mudar de Forma', NA, NA, 'Como Mudar de Forma', ['gw'],
    '', { requires: ['mudar_de_forma'] }],
  [5, 'forma_de_nevoa', 'Forma de Névoa', 'Mist Form', '1 a 3 Despertares', NA, NA, CENA, ['core'],
    'Vira névoa.'],
  [5, 'um_com_a_terra', 'Um com a Terra', 'One with the Land', R2, NA, NA, 'Um dia ou mais', ['pg'],
    'Funde-se à terra do seu território e sai em outro ponto dele.', { amalgam: ['animalismo', 2], requires: ['fusao_com_a_terra'] }],
  [5, 'enxame', 'Enxame', 'Swarm', R2, NA, NA, CENA, ['tf'],
    'Vira um enxame de bichos pequenos.', { requires: ['mudar_de_forma'] }],
  [5, 'coracao_liberto', 'O Coração Liberto', 'The Unfettered Heart', G, NA, NA, PASS, ['core'],
    'Seu coração se move dentro do peito: estacas quase nunca acertam.'],
  [5, 'rosto_da_vitima', 'Rosto da Vítima', 'Face of the Victim', R1, NA, NA, 'Até Fome 5', ['lsc'], '', { requires: ['vicissitude'] }],
])

const OBLIVIO = build('oblivio', [
  [1, 'cinzas_as_cinzas', 'Cinzas às Cinzas', 'Ashes to Ashes', R1, 'Vigor + Oblívio', 'Vigor + Medicina ou Fortitude', 'Variável', ['cbg', 'pg'],
    'Desfaz um cadáver em cinzas.'],
  [1, 'grilhao_de_ligacao', 'Grilhão de Ligação', 'Binding Fetter', G, 'Raciocínio + Oblívio', NA, CENA, ['cbg', 'pg'],
    'Percebe os objetos e lugares que prendem fantasmas a este mundo.'],
  [1, 'visao_do_oblivio', 'Visão do Oblívio', 'Oblivion Sight', G, NA, NA, CENA, ['cbn', 'pg'],
    'Enxerga no escuro total e vê fantasmas.'],
  [1, 'capa_de_sombra', 'Capa de Sombra', 'Shadow Cloak', G, NA, NA, PASS, ['cbn', 'pg', 'fol'],
    'As sombras te cobrem: ajuda a se esconder e a intimidar.'],
  [2, 'bracos_de_ahriman', 'Braços de Ahriman', 'Arms of Ahriman', R1, 'Raciocínio + Oblívio', NA, 'Uma cena ou até encerrar', ['cbn', 'pg'],
    'Tentáculos de sombra que agarram e ferem.', { amalgam: ['potencia', 2] }],
  [2, 'previsao_fatal', 'Previsão Fatal', 'Fatal Prediction', R1, 'Determinação + Oblívio', 'Raciocínio + Ocultismo', '24 horas', ['pg'],
    'Vê como alguém pode se ferir em breve, e deixa isso mais provável.', { amalgam: ['auspicios', 2] }],
  [2, 'precognicao_fatal', 'Precognição Fatal', 'Fatal Precognition', R1, 'Determinação + Oblívio', NA, 'Até acontecer ou ser evitado', ['cbg'],
    'Uma visão da morte de alguém por perto.', { amalgam: ['auspicios', 2] }],
  [2, 'lancar_sombra', 'Lançar Sombra', 'Shadow Cast', R1, NA, NA, CENA, ['cbn', 'pg'],
    'Cria sombras que dão cobertura e gelam quem está nelas.'],
  [2, 'onde_o_veu_afina', 'Onde o Véu Afina', 'Where the Veil Thins', R1, 'Inteligência + Oblívio', NA, 'Um turno', ['cbg', 'pg'],
    'Mede o quanto está fina a fronteira entre vivos e mortos num lugar.'],
  [3, 'aura_de_decadencia', 'Aura de Decadência', 'Aura of Decay', R1, 'Vigor + Oblívio', 'Vigor + Medicina ou Fortitude', CENA, ['cbg', 'pg'],
    'Tudo ao redor apodrece; mortais adoecem.'],
  [3, 'banquete_de_paixao', 'Banquete de Paixão', 'Passion Feast', G, 'Determinação + Oblívio', 'Determinação + Autocontrole', PASS, ['cbg', 'pg'],
    'Mata a Fome com a paixão dos fantasmas.', { amalgam: ['fortitude', 2] }],
  [3, 'perspectiva_da_sombra', 'Perspectiva da Sombra', 'Shadow Perspective', R1, NA, NA, 'Até uma cena', ['cbn', 'pg'],
    'Vê e ouve através de uma sombra que você já viu.'],
  [3, 'servo_de_sombra', 'Servo de Sombra', 'Shadow Servant', R1, NA, NA, CENA, ['pg'],
    'Uma sombra sua que espiona e assusta.', { amalgam: ['auspicios', 1] }],
  [3, 'toque_do_oblivio', 'Toque do Oblívio', 'Touch of Oblivion', R1, NA, NA, 'Um turno', ['cbn', 'pg'],
    'Seu toque murcha a carne: dano agravado.'],
  [4, 'praga_necrotica', 'Praga Necrótica', 'Necrotic Plague', R1, 'Inteligência + Oblívio', 'Vigor + Medicina ou Fortitude', 'Variável', ['cbg', 'pg'],
    'Uma doença sobrenatural que corrói o alvo aos poucos.'],
  [4, 'profanar_o_sagrado', 'Profanar o Sagrado', 'Profane the Sanctified', R1, 'Determinação + Oblívio', 'Teste de Força de Vontade', 'Um turno', ['tf'],
    '', { requires: ['aura_de_decadencia', 'toque_do_oblivio'] }],
  [4, 'mortalha_estigia', 'Mortalha Estígia', 'Stygian Shroud', R1, NA, NA, CENA, ['cbn', 'pg'],
    'Uma escuridão espessa e fria toma conta de uma área.'],
  [4, 'garra_umbrosa', 'Garra Umbrosa', 'Umbrous Clutch', '1 Despertar + 1 mancha', 'Raciocínio + Oblívio', 'Destreza + Raciocínio', 'Instantâneo', ['sab'], ''],
  [5, 'a_escuridao_interior', 'A Escuridão Interior', 'The Darkness Within', R2, 'Manipulação + Oblívio', 'Autocontrole + Determinação', CENA, ['tf'], ''],
  [5, 'passo_das_sombras', 'Passo das Sombras', 'Shadow Step', R1, NA, NA, 'Um turno', ['cbn', 'pg'],
    'Entra numa sombra e sai em outra.'],
  [5, 'skuld_realizado', 'Skuld Realizado', 'Skuld Fulfilled', R2, 'Vigor + Oblívio', 'Vigor + Vigor ou Fortitude', 'Variável', ['cbg', 'pg'],
    'Faz voltar no alvo uma doença ou ferida antiga, de antes do Abraço.'],
  [5, 'avatar_tenebroso', 'Avatar Tenebroso', 'Tenebrous Avatar', R2, NA, NA, CENA, ['cbn', 'pg'],
    'Vira uma sombra viva: passa por frestas e só fogo e sol te ferem.'],
  [5, 'espirito_murcho', 'Espírito Murcho', 'Withering Spirit', '2 Despertares + manchas', 'Determinação + Oblívio', 'Determinação + Ocultismo ou Fortitude', 'Um turno', ['cbg'], ''],
])

const FEITICARIA = build('feiticaria', [
  [1, 'vitae_corrosiva', 'Vitae Corrosiva', 'Corrosive Vitae', '1 ou mais Despertares', NA, NA, NA, ['core'],
    'Seu sangue corrói objetos e materiais (não seres vivos).'],
  [1, 'moldar_o_sacramento', 'Moldar o Sacramento Sanguíneo', 'Shape the Sanguine Sacrament', G, 'Manipulação + Feitiçaria de Sangue', NA, CENA, ['wt', 'tf'], ''],
  [1, 'gosto_de_sangue', 'Gosto de Sangue', 'A Taste for Blood', G, 'Determinação + Feitiçaria de Sangue', NA, NA, ['core'],
    'Prova o sangue e descobre ressonância, Potência, geração, diablerie.'],
  [1, 'feiticaria_kolduna', 'Feitiçaria Kolduna', 'Koldunic Sorcery', '1 Despertar + dano agravado', 'Determinação + Feitiçaria de Sangue', 'Raciocínio ou Determinação + Ofuscação', CENA, ['bs'],
    'Só Tzimisce.'],
  [2, 'maldicao_do_sangue', 'Maldição do Sangue', "Blood's Curse", R1, 'Inteligência + Feitiçaria de Sangue', 'Vigor + Ocultismo ou Fortitude', 'Até o amanhecer', ['gw'], ''],
  [2, 'extinguir_a_vitae', 'Extinguir a Vitae', 'Extinguish Vitae', R1, 'Inteligência + Feitiçaria de Sangue', 'Vigor + Autocontrole', NA, ['core'],
    'Aumenta a Fome de outro vampiro que você vê.'],
  [2, 'vasculhar_segredos', 'Vasculhar Segredos', 'Scour Secrets', R1, 'Inteligência + Feitiçaria de Sangue', NA, 'Uma noite', ['pg'],
    'Lê pilhas de documentos num instante procurando algo.'],
  [2, 'vinculum_magnum', 'Vinculum Magnum', 'Vinculum Magnum', G, NA, NA, PASS, ['cod'], ''],
  [3, 'sangue_de_potencia', 'Sangue de Potência', 'Blood of Potency', R1, 'Determinação + Feitiçaria de Sangue', NA, 'Uma cena ou noite', ['core'],
    'Aumenta por um tempo a sua Potência de Sangue.'],
  [3, 'toque_do_escorpiao', 'Toque do Escorpião', "Scorpion's Touch", '1 ou mais Despertares', 'Força + Feitiçaria de Sangue', 'Vigor + Ocultismo ou Fortitude', CENA, ['core'],
    'Transforma o seu sangue num veneno que paralisa.'],
  [3, 'laco_transitivo', 'Laço Transitivo', 'Transitive Bond', R1, NA, NA, NA, ['sab'], ''],
  [3, 'ondulacoes_do_coracao', 'Ondulações do Coração', 'Ripples of the Heart', R1, NA, NA, NA, ['bsl'], ''],
  [4, 'roubo_de_vitae', 'Roubo de Vitae', 'Theft of Vitae', R1, 'Raciocínio + Feitiçaria de Sangue', 'Raciocínio + Ocultismo', 'Uma alimentação', ['core'],
    'Puxa o sangue de alguém à distância direto pra sua boca.'],
  [4, 'egide_de_sangue', 'Égide de Sangue', 'Blood Aegis', '1 ou mais Despertares', NA, NA, 'Uma cena ou até gastar', ['pg'],
    'Um escudo de sangue que segura o dano.'],
  [4, 'vitae_fulminante', 'Vitae Fulminante', 'Fulminating Vitae', R2, 'Vigor + Feitiçaria de Sangue', 'Raciocínio + Atletismo', 'Até o amanhecer', ['tf'], ''],
  [4, 'marionete', 'Marionete', 'Marionette', R1, 'Manipulação + Feitiçaria de Sangue', 'Vigor + Ocultismo ou Fortitude', 'Um turno por margem', ['tf'],
    '', { requires: ['moldar_o_sacramento'] }],
  [5, 'caricia_de_baal', 'Carícia de Baal', "Baal's Caress", '1 ou mais Despertares', 'Força + Feitiçaria de Sangue', 'Vigor + Ocultismo ou Fortitude', CENA, ['core'],
    'Seu sangue vira um veneno que faz dano agravado.'],
  [5, 'caldeirao_de_sangue', 'Caldeirão de Sangue', 'Cauldron of Blood', '1 Despertar + 1 mancha', 'Determinação + Feitiçaria de Sangue', 'Autocontrole + Ocultismo ou Fortitude', 'Um turno', ['core'],
    'Ferve o sangue do alvo por dentro.'],
  [5, 'recuperacao_de_vitae', 'Recuperação de Vitae', 'Reclamation of Vitae', '1 ou mais manchas', NA, NA, NA, ['sab'], ''],
])

export const VTM_POWERS: VtmPower[] = [
  ...ANIMALISMO, ...AUSPICIOS, ...CELERIDADE, ...DOMINACAO, ...FORTITUDE, ...OFUSCACAO,
  ...POTENCIA, ...PRESENCA, ...METAMORFOSE, ...OBLIVIO, ...FEITICARIA,
]

export const VTM_POWER_BY_ID = new Map(VTM_POWERS.map((p) => [p.id, p]))

/** Características de cada disciplina (tipo e o que ameaça a Máscara). */
export const VTM_DISCIPLINE_INFO: Record<VtmDiscipline, { type: string; masquerade: string; resonance: string; summary: string }> = {
  animalismo:  { type: 'Mental', masquerade: 'Baixa a média', resonance: 'Sangue animal', summary: 'Laço com os animais e com a Besta.' },
  auspicios:   { type: 'Mental', masquerade: 'Baixa', resonance: 'Fleumático', summary: 'Sentidos sobrenaturais, leitura de mentes e do futuro.' },
  celeridade:  { type: 'Física', masquerade: 'Média a alta', resonance: 'Colérico', summary: 'Velocidade e reflexos sobrenaturais.' },
  dominacao:   { type: 'Mental', masquerade: 'Baixa', resonance: 'Fleumático', summary: 'Ordens que a mente do alvo obedece, e memórias apagadas.' },
  fortitude:   { type: 'Física', masquerade: 'Baixa a média', resonance: 'Melancólico', summary: 'Resistência a dano, a coerção e às perdições.' },
  metamorfose: { type: 'Física', masquerade: 'Alta', resonance: 'Sangue animal', summary: 'Mudar o corpo: garras, formas animais, névoa.' },
  oblivio:     { type: 'Mental', masquerade: 'Média', resonance: 'Melancólico', summary: 'Sombras e a terra dos mortos. Despertar com 1 ou 10 dá uma mancha.' },
  ofuscacao:   { type: 'Mental', masquerade: 'Baixa', resonance: 'Melancólico', summary: 'Sumir, não ser notado, mudar de rosto.' },
  potencia:    { type: 'Física', masquerade: 'Média a alta', resonance: 'Colérico', summary: 'Força sobrenatural.' },
  presenca:    { type: 'Mental', masquerade: 'Baixa a média', resonance: 'Sanguíneo', summary: 'Emoções dos outros: encanto, medo, devoção.' },
  feiticaria:  { type: 'Mental', masquerade: 'Média a alta', resonance: 'Sanguíneo', summary: 'Magia de sangue e rituais.' },
  alquimia:    { type: 'Mental', masquerade: 'Média', resonance: 'Nenhuma', summary: 'Fórmulas destiladas do sangue ralo.' },
}
