import type { VtmBook } from './vtmPowers'

// ────────────────────────────────────────────────────────
// Rituais de Feitiçaria de Sangue, cerimônias de Oblívio e fórmulas de
// Alquimia de Sangue-Ralo (V5). Só nome (traduzido por nós, com o original
// do lado), nível, livro e, nas cerimônias, o poder exigido. Cada um vale
// um id "ritual.x", "cerimonia.x" ou "formula.x" na ficha.
// ────────────────────────────────────────────────────────

export type VtmRiteKind = 'ritual' | 'cerimonia' | 'formula'

export interface VtmRite {
  id:     string
  kind:   VtmRiteKind
  level:  number
  name:   string
  en:     string
  books:  VtmBook[]
  /** Cerimônia: precisa de um destes poderes de Oblívio (ids completos). */
  requires?: string[]
}

export const VTM_RITE_RULES: Record<VtmRiteKind, { label: string; plural: string; disc: 'feiticaria' | 'oblivio' | 'alquimia'; rule: string }> = {
  ritual: {
    label: 'Ritual', plural: 'Rituais', disc: 'feiticaria',
    rule: 'Teste de Inteligência + Feitiçaria de Sangue, dificuldade nível + 1; um Despertar por nível (salvo indicação); cinco minutos por nível. Na criação, um ritual de graça por ponto; os outros custam XP (nível × 3) e semanas de estudo.',
  },
  cerimonia: {
    label: 'Cerimônia', plural: 'Cerimônias', disc: 'oblivio',
    rule: 'Teste de Determinação + Oblívio, dificuldade nível + 1; um Despertar (salvo indicação); cinco minutos por nível; precisa de um poder de Oblívio específico. Custam XP (nível × 3).',
  },
  formula: {
    label: 'Fórmula', plural: 'Fórmulas', disc: 'alquimia',
    rule: 'Uma fórmula de graça por ponto de Alquimia; as outras custam XP (nível × 3). Destilação por Athanor Corporis (Vigor + Alquimia), Calcinatio (Manipulação + Alquimia) ou Fixatio (Inteligência + Alquimia).',
  },
}

type Row = [level: number, key: string, name: string, en: string, books: VtmBook[], requires?: string[]]

function build(kind: VtmRiteKind, rows: Row[]): VtmRite[] {
  return rows.map(([level, key, name, en, books, requires]) => ({
    id: `${kind}.${key}`, kind, level, name, en, books,
    requires: requires?.map((r) => `oblivio.${r}`),
  }))
}

const RITUAIS = build('ritual', [
  [1, 'astromancia', 'Astromancia', 'Astromancy', ['bs']],
  [1, 'beelzebeatit', 'Beelzebeatit', 'Beelzebeatit', ['sab']],
  [1, 'prender_a_lingua', 'Prender a Língua Acusadora', 'Bind the Accusing Tongue', ['bs']],
  [1, 'apocrifo_de_sangue', 'Apócrifo de Sangue', 'Blood Apocrypha', ['bna']],
  [1, 'andanca_de_sangue', 'Andança de Sangue', 'Blood Walk', ['core']],
  [1, 'mensagem_sangrenta', 'Mensagem Sangrenta', 'Bloody Message', ['ltsr']],
  [1, 'sangue_em_agua', 'Sangue em Água', 'Blood to Water', ['gw']],
  [1, 'apego_do_inseto', 'Apego do Inseto', 'Clinging of the Insect', ['core']],
  [1, 'persuadir_o_jardim', 'Persuadir o Jardim', 'Coax the Garden', ['cbg']],
  [1, 'criar_pedra_de_sangue', 'Criar Pedra de Sangue', 'Craft Bloodstone', ['core']],
  [1, 'apagar_o_medo', 'Apagar o Medo', 'Douse the Fear', ['cbg', 'pg']],
  [1, 'enriquecer_o_sangue', 'Enriquecer o Sangue', 'Enrich the Blood', ['fr']],
  [1, 'protecao_do_rebanho_menor', 'Proteção do Rebanho (Menor)', 'Herd Ward (Minor)', ['ltsr']],
  [1, 'protecao_de_carta', 'Proteção de Carta', 'Letter Ward', ['ltsr']],
  [1, 'revelar_a_trilha_carmesim', 'Revelar a Trilha Carmesim', 'Revealing the Crimson Trail', ['gw']],
  [1, 'selar_a_marca', 'Selar a Marca', 'Seal the Brand', ['pg']],
  [1, 'memoria_compartilhada', 'Memória Compartilhada', 'Shared Memory', ['im']],
  [1, 'despertar_revigorado', 'Despertar Revigorado', "Wake with Evening's Freshness", ['core']],
  [1, 'protecao_contra_carnicais', 'Proteção contra Carniçais', 'Ward Against Ghouls', ['core']],
  [1, 'missiva_de_sangue', 'Missiva de Sangue', 'Blood Missive', ['lsc']],
  [1, 'noticias_sanguineas', 'Notícias Sanguíneas', 'Sanguine Tidings', ['lsc']],
  [1, 'preservacao', 'Preservação', 'Preservation', ['cod']],
  [1, 'rito_de_apresentacao', 'Rito de Apresentação', 'Rite of Introduction', ['cod']],
  [2, 'como_nevoa_na_agua', 'Como Névoa na Água', 'As Fog on Water', ['pg']],
  [2, 'restos_da_aura', 'Chamar os Restos da Aura', "Calling the Aura's Remnants", ['cf']],
  [2, 'calix_secretus', 'Calix Secretus', 'Calix Secretus', ['pg']],
  [2, 'falar_com_o_senhor', 'Falar com o Senhor', 'Communicate with Kindred Sire', ['core']],
  [2, 'mestre_artesao', 'Mestre Artesão', 'Craftmaster', ['bs']],
  [2, 'profundezas_do_pesadelo', 'Profundezas do Pesadelo', 'Depths of Nightmare', ['bs']],
  [2, 'agarrao_elemental', 'Agarrão Elemental', 'Elemental Grasp', ['bs']],
  [2, 'realcar_a_discrasia', 'Realçar a Discrasia', 'Enhance Dyscrasia', ['fr']],
  [2, 'olhos_de_babel', 'Olhos de Babel', 'Eyes of Babel', ['core']],
  [2, 'iluminar_a_trilha', 'Iluminar a Trilha da Presa', 'Illuminate Trail of Prey', ['core']],
  [2, 'o_sangue_do_amor', 'O Sangue do Amor', "Le Sang de l'Amour", ['bs', 'bsl']],
  [2, 'toque_soporifico', 'Toque Soporífico', 'Soporific Touch', ['cam', 'pg']],
  [2, 'silentia_mortis', 'Silentia Mortis', 'Silentia Mortis', ['bs']],
  [2, 'mortalha_de_silencio', 'Mortalha de Silêncio', 'Shroud of Silence', ['fr']],
  [2, 'memoria_roubada', 'Memória Roubada', 'Stolen Memory', ['im']],
  [2, 'tiamat_reluz', 'Tiamat Reluz', 'Tiamat Glistens', ['bs']],
  [2, 'verdade_do_sangue', 'Verdade do Sangue', 'Truth of Blood', ['core']],
  [2, 'subterraneo_invisivel', 'Subterrâneo Invisível', 'Unseen Underground', ['fol']],
  [2, 'jardim_de_visceras', 'Jardim de Vísceras', 'Viscera Garden', ['bs']],
  [2, 'protecao_contra_espiritos', 'Proteção contra Espíritos', 'Ward against Spirits', ['core']],
  [2, 'circulo_contra_carnicais', 'Círculo de Proteção contra Carniçais', 'Warding Circle against Ghouls', ['core']],
  [2, 'teia_da_fome', 'Teia da Fome', 'Web of Hunger', ['fol']],
  [3, 'maos_de_lamina', 'Mãos de Lâmina', 'Bladed Hands', ['cf']],
  [3, 'banquete_sem_sangue', 'Banquete sem Sangue', 'Bloodless Feast', ['fr']],
  [3, 'sigilo_de_sangue', 'Sigilo de Sangue', 'Blood Sigil', ['bs']],
  [3, 'vigor_comunal', 'Vigor Comunal', 'Communal Vigor', ['sab']],
  [3, 'chamado_de_dagon', 'Chamado de Dagon', "Dagon's Call", ['core']],
  [3, 'desviar_a_ruina_de_madeira', 'Desviar a Ruína de Madeira', 'Deflection of Wooden Doom', ['core']],
  [3, 'abrigo_elemental', 'Abrigo Elemental', 'Elemental Shelter', ['bs']],
  [3, 'essencia_do_ar', 'Essência do Ar', 'Essence of Air', ['core']],
  [3, 'olhos_do_passado', 'Olhos do Passado', 'Eyes of the Past', ['cf']],
  [3, 'fogo_no_sangue', 'Fogo no Sangue', 'Fire in the Blood', ['cbg', 'pg']],
  [3, 'andar_no_fogo', 'Andar no Fogo', 'Firewalker', ['core']],
  [3, 'ruina_galvanica', 'Ruína Galvânica', 'Galvanic Ruination', ['sab']],
  [3, 'mente_gentil', 'Mente Gentil', 'Gentle Mind', ['cf']],
  [3, 'crisalida_sombria', 'Crisálida Sombria', 'Grim Chrysalis', ['tf']],
  [3, 'casa_assombrada', 'Casa Assombrada', 'Haunted House', ['cf']],
  [3, 'protecao_do_rebanho_maior', 'Proteção do Rebanho (Maior)', 'Herd Ward (Major)', ['ltsr']],
  [3, 'ilusao_de_morte_pacifica', 'Ilusão de Morte Pacífica', 'Illusion of Peaceful Death', ['cf']],
  [3, 'ilusao_de_perfeicao', 'Ilusão de Perfeição', 'Illusion of Perfection', ['cf']],
  [3, 'nepente', 'Nepente', 'Nepenthe', ['bs']],
  [3, 'um_com_a_lamina', 'Um com a Lâmina', 'One with the Blade', ['cam', 'pg']],
  [3, 'vigia_sanguineo', 'Vigia Sanguíneo', 'Sanguine Watcher', ['cf']],
  [3, 'ver_com_os_olhos_do_ceu', 'Ver com os Olhos do Céu', "Seeing with the Sky's Eyes", ['bs']],
  [3, 'buscando_tiamat', 'Buscando Tiamat', 'Seeking Tiamat', ['bs']],
  [3, 'sono_de_judas', 'Sono de Judas', 'Sleep of Judas', ['ltsr']],
  [3, 'alma_do_homunculo', 'Alma do Homúnculo', 'Soul of the Hemonculus', ['bs']],
  [3, 'pedra_da_forma_verdadeira', 'Pedra da Forma Verdadeira', 'Stone of the True Form', ['bs']],
  [3, 'a_mudanca_invisivel', 'A Mudança Invisível', 'The Unseen Change', ['cf']],
  [3, 'invasao', 'Invasão', 'Trespass', ['bs']],
  [3, 'aruspice_viral', 'Arúspice Viral', 'Viral Haruspex', ['bs']],
  [3, 'protecao_contra_lupinos', 'Proteção contra Lupinos', 'Ward against Lupines', ['core']],
  [3, 'circulo_contra_espiritos', 'Círculo de Proteção contra Espíritos', 'Warding Circle against Spirits', ['core']],
  [4, 'balsamo_de_bathory', 'Bálsamo de Báthory', 'Balm of Bathory', ['tf']],
  [4, 'comandar_o_inanimado', 'Comandar o Inanimado', 'Compel the Inanimate', ['bs']],
  [4, 'defesa_do_refugio_sagrado', 'Defesa do Refúgio Sagrado', 'Defense of the Sacred Haven', ['core']],
  [4, 'consulta_a_egregora', 'Consulta à Egrégora', 'Egregore Consultation', ['bs']],
  [4, 'olhos_do_gaviao_noturno', 'Olhos do Gavião Noturno', 'Eyes of the Nighthawk', ['core']],
  [4, 'banquete_de_cinzas', 'Banquete de Cinzas', 'Feast of Ashes', ['pg']],
  [4, 'memoria_guiada', 'Memória Guiada', 'Guided Memory', ['pg']],
  [4, 'passagem_incorporea', 'Passagem Incorpórea', 'Incorporeal Passage', ['core']],
  [4, 'inocencia_do_coracao', 'Inocência do Coração de Criança', "Innocence of the Child's Heart", ['cf']],
  [4, 'veu_da_inocencia', 'Véu da Inocência', "Innocence's Veil", ['gw']],
  [4, 'correntes_invisiveis', 'Correntes Invisíveis de Amarração', 'Invisible Chains of Binding', ['pg']],
  [4, 'sustento_da_terra', 'Sustento da Terra', "Land's Sustenance", ['bs']],
  [4, 'rasgar_a_terra_doce', 'Rasgar a Terra Doce', 'Rending the Sweet Earth', ['cf']],
  [4, 'cavalgar_a_veia_da_terra', 'Cavalgar a Veia da Terra', "Riding the Earth's Vein", ['bs']],
  [4, 'maldicao_proteana', 'Maldição Proteana', 'Protean Curse', ['cf']],
  [4, 'protecao_contra_cainitas', 'Proteção contra Cainitas', 'Ward against Cainites', ['core']],
  [4, 'circulo_contra_lupinos', 'Círculo de Proteção contra Lupinos', 'Warding Circle against Lupines', ['core']],
  [4, 'buscar_a_vitae_reunida', 'Buscar a Vitae Reunida', 'Seek the Gathered Vitae', ['lsc']],
  [5, 'antebrachia_ignium', 'Antebrachia Ignium', 'Antebrachia Ignium', ['cbg', 'pg']],
  [5, 'libertacao_da_atrocidade', 'Libertação da Atrocidade', "Atrocity's Release", ['gw']],
  [5, 'dominio', 'Domínio', 'Dominion', ['pg']],
  [5, 'fartura_do_eden', 'Fartura do Éden', "Eden's Bounty", ['cbg']],
  [5, 'ataque_elemental', 'Ataque Elemental', 'Elemental Attack', ['bs']],
  [5, 'fuga_ao_santuario', 'Fuga ao Verdadeiro Santuário', 'Escape to True Sanctuary', ['core']],
  [5, 'rei_pescador', 'Rei Pescador', 'Fisher King', ['bs']],
  [5, 'coracao_de_pedra', 'Coração de Pedra', 'Heart of Stone', ['core']],
  [5, 'vigor_redespertado', 'Vigor Redespertado', 'Reawakened Vigor', ['gw']],
  [5, 'haste_da_dissolucao', 'Haste da Dissolução Tardia', 'Shaft of Belated Dissolution', ['core']],
  [5, 'portal_simulacro', 'Portal Simulacro', 'Simulacrum Gate', ['sab']],
  [5, 'transferir_a_alma', 'Transferir a Alma', 'Transferring the Soul', ['fol']],
  [5, 'circulo_contra_cainitas', 'Círculo de Proteção contra Cainitas', 'Warding Circle against Cainites', ['core']],
  [5, 'fundacao_da_capela', 'Fundação da Capela', 'Foundation of the Chantry', ['cod']],
])

const CERIMONIAS = build('cerimonia', [
  [1, 'dom_da_falsa_vida', 'Dom da Falsa Vida', 'Gift of False Life', ['cbg', 'pg'], ['cinzas_as_cinzas']],
  [1, 'pedra_que_sabe', 'Pedra que Sabe', 'Knowing Stone', ['fol'], ['cinzas_as_cinzas', 'grilhao_de_ligacao']],
  [1, 'invocar_espirito', 'Invocar Espírito', 'Summon Spirit', ['cbg', 'pg'], ['grilhao_de_ligacao']],
  [1, 'chamado_do_viajante', 'Chamado do Viajante', "Traveler's Call", ['cbg'], ['visao_do_oblivio']],
  [2, 'reliquia_de_cinzas', 'Relíquia de Cinzas', 'Ashen Relic', ['bna'], ['cinzas_as_cinzas', 'visao_do_oblivio']],
  [2, 'despertar_o_servo', 'Despertar o Servo Homúnculo', 'Awaken the Homuncular Servant', ['cbg', 'pg'], ['onde_o_veu_afina']],
  [2, 'cegar_o_olho_de_liga', 'Cegar o Olho de Liga', 'Blinding the Alloy Eye', ['sab'], ['lancar_sombra']],
  [2, 'compelir_espirito', 'Compelir Espírito', 'Compel Spirit', ['cbg', 'pg'], ['onde_o_veu_afina']],
  [2, 'boca_de_ahriman', 'Boca de Ahriman', 'Maw of Ahriman', ['bsl']],
  [3, 'traje_de_cadaver', 'Criar Traje de Cadáver', 'Create Corpse Suit', ['tf'], ['perspectiva_da_sombra', 'toque_do_oblivio']],
  [3, 'golem_de_carne', 'Criar Golem de Carne', 'Create Flesh Golem', ['tf'], ['aura_de_decadencia', 'praga_necrotica']],
  [3, 'fortezza_sindonica', 'Fortezza Sindonica', 'Fortezza Sindonica', ['tab'], ['onde_o_veu_afina']],
  [3, 'harrowhaunt', 'Assombração do Tormento', 'Harrowhaunt', ['sab'], ['aura_de_decadencia']],
  [3, 'hospedar_espirito', 'Hospedar Espírito', 'Host Spirit', ['cbg', 'pg'], ['aura_de_decadencia']],
  [3, 'tecer_o_veu', 'Tecer o Véu', 'Knit the Veil', ['tab'], ['onde_o_veu_afina']],
  [3, 'nome_do_pai', 'Nome do Pai', 'Name of the Father', ['cbg'], ['perspectiva_da_sombra']],
  [3, 'sono_raso', 'Sono Raso', 'Shallow Slumber', ['gw'], ['banquete_de_paixao', 'toque_do_oblivio']],
  [3, 'hordas_cambaleantes', 'Hordas Cambaleantes', 'Shambling Hordes', ['cbg', 'pg'], ['aura_de_decadencia']],
  [3, 'sabedoria_dos_mortos', 'Sabedoria dos Mortos', 'Wisdom of the Dead', ['bna'], ['onde_o_veu_afina', 'visao_do_oblivio']],
  [3, 'mao_do_infortunio', 'Mão do Infortúnio', "Misfortune's Hand", ['cod'], ['servo_de_sombra', 'toque_do_oblivio']],
  [4, 'conspurcar_o_receptaculo', 'Conspurcar o Receptáculo', 'Befoul Vessel', ['sab'], ['praga_necrotica']],
  [4, 'prender_o_espirito', 'Prender o Espírito', 'Bind the Spirit', ['cbg', 'pg'], ['praga_necrotica']],
  [4, 'prender_a_forma_mortal', 'Prender à Forma Mortal', 'Bind to Mortal Form', ['tf'], ['praga_necrotica', 'skuld_realizado']],
  [4, 'estertor', 'Estertor', 'Death Rattle', ['tab'], ['precognicao_fatal']],
  [4, 'partir_o_veu', 'Partir o Véu', 'Split the Veil', ['cbg', 'pg'], ['praga_necrotica']],
  [5, 'ex_nihilo', 'Ex Nihilo', 'Ex Nihilo', ['cbg'], ['espirito_murcho']],
  [5, 'dom_da_vida_verdadeira', 'Dom da Vida Verdadeira', 'Gift of True Life', ['tf'], ['praga_necrotica', 'banquete_de_paixao']],
  [5, 'bencao_lazarena', 'Bênção Lazarena', 'Lazarene Blessing', ['cbg', 'pg'], ['skuld_realizado']],
  [5, 'poco_da_contemplacao', 'Poço da Contemplação', 'Pit of Contemplation', ['cbg'], ['avatar_tenebroso']],
])

const FORMULAS = build('formula', [
  [1, 'pintura_corporal', 'Pintura Corporal', 'Body Paint', ['bs']],
  [1, 'hora_do_checkout', 'Hora do Checkout', 'Checkout Time', ['bs']],
  [1, 'elevar', 'Elevar', 'Elevate', ['bs']],
  [1, 'longo_alcance', 'Longo Alcance', 'Far Reach', ['core']],
  [1, 'mancha_no_alimento', 'Mancha no Alimento', 'Food Stain', ['bs']],
  [1, 'ruina_do_carcereiro', 'Ruína do Carcereiro', "Gaoler's Bane", ['wt']],
  [1, 'neblina', 'Neblina', 'Haze', ['core']],
  [1, 'lingua_mercurial', 'Língua Mercurial', 'Mercurian Tongue', ['pg']],
  [1, 'na_tomada', 'Na Tomada', 'Plug-In', ['pg']],
  [1, 'sombra_portatil', 'Sombra Portátil', 'Portable Shade', ['sab']],
  [1, 'falar_do_coracao', 'Falar do Coração', 'Speak From the Heart', ['bs']],
  [1, 'disciplina_falsificada_1', 'Disciplina Falsificada (1)', 'Counterfeit Discipline •', ['core']],
  [2, 'torpor_avancado', 'Torpor Avançado', 'Advanced Torpor', ['bs']],
  [2, 'surpresa_de_luz_negra', 'Surpresa de Luz Negra', 'Blacklight Surprise', ['bs']],
  [2, 'sangue_de_mandagloire', 'Sangue de Mandagloire', 'Blood of Mandagloire', ['si']],
  [2, 'estado_azul', 'Estado Azul', 'Blue State', ['bs']],
  [2, 'envolver', 'Envolver', 'Envelop', ['core']],
  [2, 'lista_de_amigos', 'Lista de Amigos', 'Friends List', ['pg']],
  [2, 'espelho_da_confianca', 'Espelho da Confiança', 'Mirror of Trust', ['si']],
  [2, 'molho_picante_do_red', 'Molho Picante do Red', "Red's Flaming Hot Sauce", ['wt']],
  [2, 'cheirinhos', 'Cheirinhos', 'Whiff-Its', ['gw']],
  [2, 'disciplina_falsificada_2', 'Disciplina Falsificada (2)', 'Counterfeit Discipline ••', ['core']],
  [3, 'sangrar_ate_o_fim', 'Sangrar até o Fim', 'Bleed Out', ['tf']],
  [3, 'flashback_quimico', 'Flashback Químico', 'Chemically-Induced Flashback', ['cbg']],
  [3, 'preparar_ashe', 'Preparar Ashe', 'Concoct Ashe', ['cbg']],
  [3, 'pele_de_diamante', 'Pele de Diamante', 'Diamond Skin', ['bs']],
  [3, 'desfracionar', 'Desfracionar', 'Defractionate', ['core']],
  [3, 'ferrao_de_presa', 'Ferrão de Presa', 'Fang-Stinger', ['si']],
  [3, 'pele_de_fogo', 'Pele de Fogo', 'Fireskin', ['bs']],
  [3, 'fluido_congelante', 'Fluido Congelante', 'Freezer Fluid', ['si']],
  [3, 'correntes_hospitalares', 'Correntes Hospitalares', 'Hospital Chains', ['bs']],
  [3, 'mandagloire', 'Mandagloire', 'Mandagloire', ['pg']],
  [3, 'pureza_marciana', 'Pureza Marciana', 'Martian Purity', ['bs']],
  [3, 'sem_mascara', 'Sem Máscara', 'Mask Off', ['bs']],
  [3, 'queimadura_sob_demanda', 'Queimadura sob Demanda', 'On-Demand Sunburn', ['sab']],
  [3, 'hieros_gamos_profano', 'Hieros Gamos Profano', 'Profane Hieros Gamos', ['core']],
  [3, 'boato', 'Boato', 'Rumor', ['pg']],
  [3, 'deter_a_areia', 'Deter a Areia que Cai', 'Stay the Falling Sand', ['wt']],
  [3, 'saraimu', 'Saraimu', 'Saraimu', ['tf']],
  [3, 'tanque', 'Tanque', 'Tank', ['pg']],
  [3, 'carinho', 'Carinho', 'TLC', ['bs']],
  [3, 'trolar_os_devotos', 'Trolar os Devotos', 'Troll the Pious', ['bs']],
  [3, 'disciplina_falsificada_3', 'Disciplina Falsificada (3)', 'Counterfeit Discipline •••', ['core']],
  [4, 'impulso_aereo', 'Impulso Aéreo', 'Airborne Momentum', ['core']],
  [4, 'imitador', 'Imitador', 'Copycat', ['bs']],
  [4, 'canalizar_disciplina', 'Canalizar Disciplina', 'Discipline Channeling', ['cbg']],
  [4, 'condutor_meio_vivo', 'Condutor Meio-Vivo', 'Half-Living Conductor', ['bs']],
  [4, 'perna_oca', 'Perna Oca', 'Hollow Leg', ['wt']],
  [4, 'caixinha_de_suco', 'Caixinha de Suco', 'Juice Box', ['gw']],
  [4, 'estado_vermelho', 'Estado Vermelho', 'Red State', ['bs']],
  [4, 'curto_circuito', 'Curto-Circuito', 'Short Circuit', ['pg']],
  [4, 'personalidade_toxica', 'Personalidade Tóxica', 'Toxic Personality', ['pg']],
  [4, 'glutamato_de_vitae', 'Glutamato de Vitae', 'Vitae MSG', ['bs']],
  [4, 'disciplina_falsificada_4', 'Disciplina Falsificada (4)', 'Counterfeit Discipline ••••', ['core']],
  [5, 'despertar_o_adormecido', 'Despertar o Adormecido', 'Awaken the Sleeper', ['core']],
  [5, 'modo_besta', 'Modo Besta', 'Beast Mode', ['gw']],
  [5, 'a_bomba', 'A Bomba', 'Da Bomb', ['tf']],
  [5, 'amaranto_florescente', 'Amaranto Florescente', 'Flowering Amaranth', ['pg']],
  [5, 'momento_de_clareza', 'Momento de Clareza', 'Moment of Clarity', ['pg']],
  [5, 'fluxo_de_saturno', 'Fluxo de Saturno', "Saturn's Flux", ['bs']],
])

export const VTM_RITES: VtmRite[] = [...RITUAIS, ...CERIMONIAS, ...FORMULAS]
export const VTM_RITE_BY_ID = new Map(VTM_RITES.map((r) => [r.id, r]))
